version: '3.7'
services:
  jenkins:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
#      - ./jenkins.yaml:/var/jenkins_home/jenkins.yaml
volumes:
  jenkins_home:
